config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # User routes
  get "/signup", to: "users#new"
  get "/", to: "users#homepage", as: "home"
  resources :users, only: [:show, :create]

  # Session routes

  get "/login", to: "sessions#new", as: "login"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: "logout"

  # Flight route

  get "/flights/search/:id", to: "flights#search", as: "flight_search"

  # Vacation routes

  get "/vacations", to: "vacations#index", as: "vacations"
  get "/vacations/new", to: "vacations#new", as: "new_vacation"
  get "/vacations/:id", to: "vacations#show", as: "vacation"
  post "/vacations", to: "vacations#create"
  post "/vacations/finalize/:id", to: "vacations#finalize", as: "finalize_vacation"
  post "/vacations/:vacation_id/:flight_id", to: "vacations#add_flight"

  # VacationFlights routes

  resources :vacation_flights, only: [:create, :destroy]

  resources :hotel_stays, only: [:create, :destroy]
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :user
  has_many :hotel_stays
  has_many :hotels, through: :hotel_stays
  has_many :vacation_flights
  has_many :flights, through: :vacation_flights

  validates :name, :start_date, :user, presence: true

  def last_vacation_flight
    vacation_flights.max_by do |vac_flight|
      vac_flight.flight.end_time
    end
  end

  def last_flight
    last_vacation_flight&.flight
  end

  def last_hotel_stay
    hotel_stays.max_by(&:check_out_time)
  end

  def need_to_book_hotel?
    if last_hotel_stay.nil? && last_flight.nil?
      return false
    elsif last_hotel_stay.nil?
      return true
    end

    last_hotel_stay.check_out_time < last_flight.end_time
  end

  def first_origin
    flights.min_by(&:start_time)&.origin
  end

  def cur_city
    if last_flight.nil?
      return nil
    end

    last_flight.destination
  end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :authorized

  def index
    @vacations = Vacation.where(user_id: user.id)
  end

  def show
    if user.id != Vacation.find(params[:id]).user_id
      redirect_to login_path
    end
    @cities = City.all.sort_by(&:name)
    @vacation = Vacation.find(params[:id])
    @most_recent_flight = @vacation.last_vacation_flight
    if @vacation.end_date
      render :show_final
    else
      render :show
    end
  end

  def new
    @vacation = Vacation.new
    @user_id = session[:user_id]
  end

  def create
    @vacation = Vacation.new(vacation_params)
    if @vacation.valid?
      @vacation.save
      redirect_to vacation_path(@vacation)
    else
      @vacation_with_errors = @vacation
      @vacation = Vacation.new
      render :new
    end
  end

  def finalize
    @vacation = Vacation.find(params[:id])
    @vacation.update(end_date: @vacation.last_flight.end_time.to_date)
    redirect_to vacation_path(@vacation)
  end

  # def add_flight
  #   VacationFlight.create(vacation_id: params[:vacation_id], flight_id: params[:flight_id])
  #   redirect_to vacation_path(params[:vacation_id])
  # end

  # def add_hotel
  #   HotelStay.create(vacation_id: params[:vacation_id], flight_id: params[:flight_id])
  #   redirect_to vacation_path(params[:vacation_id])
  # end

  private

  def vacation_params
    params.require(:vacation).permit(:name, :user_id, :start_date, :end_date)
  end
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_show-helper.html.erb
<%= stylesheet_link_tag "vacation_show" %>
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "bootstrap-grid.min" %>
<%= stylesheet_link_tag "bootstrap.min" %>


<div class="container">
  <% if !@vacation.end_date.present? %>
    <div style='text-align:center'>
      <% if @vacation.first_origin == @vacation.cur_city && !@vacation.flights.empty? %>
        <%= button_to 'Finalize trip!', finalize_vacation_path(@vacation), :class => "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
      <% end %></div>
  <% end %>
  <div class= "row">
    <% if @most_recent_flight %>
      <div class="col-sm">
        <div class="card border-0 shadow my-5">
          <div class='card-body p-5'>
            <h2 class="col-heading">Your current flights</h2>
            <ol>
              <% @vacation.flights.each do |flight| %>
                <li>
                  <ul>
                    <li>Airline: <%= flight.airline %></li>
                    <li>Origin City: <%= flight.origin.name %></li>
                    <li>Takeoff Time: <%= flight.start_time.strftime("%m/%d/%Y") %>, <%= flight.start_time.strftime("%I:%M%p")%> </li>
                    <li>Destination City: <%= flight.destination.name %></li>
                    <li>Landing Time: <%= flight.end_time.strftime("%m/%d/%Y") %>, <%= flight.end_time.strftime("%I:%M%p") %></li>
                  </ul>
                  <br>
                </li>
              <% end %>
            </ol>
          </div> 
        </div> 
      </div>
      <div class="col-1"></div>
    <% end %>
    <% if !@vacation.hotels.empty? %>
      <div class="col-sm">
          <div class="card border-0 shadow my-5">
            <div class='card-body p-5'>
              <h2 class="col-heading">Your current hotels</h2>
              <ol>
                <% @vacation.hotel_stays.each do |hotel_stay| %>
                  <li>
                    <ul>
                      <li>City: <%= hotel_stay.hotel.city.name %></li>
                      <li>Name: <%= hotel_stay.hotel.name %></li>
                      <li>Check in time: <%= hotel_stay.check_in_time.strftime("%m/%d/%Y") %>, <%= hotel_stay.check_in_time.strftime("%I:%M%p") %></li>
                      <li>Check out time: <%= hotel_stay.check_out_time.strftime("%m/%d/%Y") %>, <%= hotel_stay.check_out_time.strftime("%I:%M%p") %></li>
                      <li>Nights in hotel: <%= (hotel_stay.check_out_time.to_date - hotel_stay.check_in_time.to_date).to_i %>
                      </ul>
                      <br>
                    </li>
                  <% end %>
                </div>
              </div>    
          </ol>
        </div>
      <% end %>
    </div>
  </div>

app/views/vacations/index.html.erb
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "bootstrap-grid.min" %>
<%= stylesheet_link_tag "bootstrap.min" %>

<%= render "layouts/nav-bar" %>

  <div class="container">
    <div class="card border-0 shadow my-5">
      <div class="card-body p-5">
        <h1 class="font-weight-light">My Vacations</h1>
        <p class="lead" style="text-align:center">Click on a vacation to see details, or make a new one below!</p>
        <p style='text-align:center'>
          <ol>
            <% @vacations.each do |vac| %>
                <li>
                  <%= link_to "#{vac.name} starting on #{vac.start_date.strftime('%m/%d/%Y')}", vacation_path(vac)%>
                </li>
            <% end %>
          </ol>
        </p>
        <div style="height: 100px"></div>
      </div>
    </div>
    <div class="p-3 mb-2">
      <%= button_to('Make a new vacation!', new_vacation_path, :class => "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2", :method => "get") %>
    </div>
  </div>

app/views/vacations/new.html.erb
<%= render "layouts/nav-bar" %>
<% if @vacation_with_errors.present? %>
  <div id='error'>
    <div class="card mx-auto border-0 shadow my-5" id="innererror" style="width: 18rem;">
      <div class="card-header">
        <strong><%= pluralize(@vacation_with_errors.errors.count, "error") %> prohibited this vacation from being created:</strong>
      </div>
      <ol class="list-group list-group-flush">
        <% @vacation_with_errors.errors.full_messages.each do |message|%>
          <li class="list-group-item"><%= message %></li>
        <% end %>
      </ol>
    </div>
  </div>
<% end %>
<div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">
      <h1 class="font-weight-light">Create a Vacation!</h1>
      <p class="lead" style="text-align:center">travelin' n doin' thingz</p>
      <p>
        <%= form_for(@vacation) do |f| %>
          <div class="form-label-group">
            <%= f.text_field :name, class: 'form-control' %>
            <label>Vacation Name</label>
          </div>
          <div class="form-label-group">
            <%= f.date_field :start_date, value: Date.today, class: 'form-control' %>
            <%= f.label 'Start Date'%>
          </div>
          <%= hidden_field_tag "vacation[user_id]", @user_id %>
          <%= f.submit "Make the vacay!", class: "btn btn-lg btn-primary btn-block text-uppercase" %>
        <% end %>
      </p>
      <div style="height: 100px"></div>
    </div>
  </div>
</div>

app/views/vacations/show.html.erb
<%= render "layouts/nav-bar" %>
<br>
<h1><%= "#{@vacation.name} starting on #{@vacation.start_date.strftime('%m/%d/%Y')}"%></h1>
<h4 style='text-align:center'>Search for flights or hotels below!</h4>
<% if flash[:errors].present? %>
  <div id='error'>
    <div class="card mx-auto border-0 shadow my-5" id="innererror" style="width: 18rem;">
      <div class="card-header">
        <strong><%= pluralize(flash[:errors].count, "error") %> prohibited this reservation from being booked:</strong>
      </div>
      <ol class="list-group list-group-flush">
        <% flash[:errors].each do |message|%>
          <li class="list-group-item"><%= message %></li>
        <% end %>
      </ol>
    </div>
  </div>
<% end %>
<%= render "show-helper" %>
<div class="container">
  <div class="row">
    <% if !@vacation.need_to_book_hotel? %>
      <div class="col-sm button">
        <%= " " %>
      </div>
      <div class="col-1 button">
        <%= " " %>
      </div>
      <div class="col-sm button">
        <% if !@vacation.hotels.empty? %>
          <%= button_to "Delete the most recent hotel", @vacation.hotel_stays.max_by(&:check_out_time), {method: :delete, class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2", id: "delete-hotel"} %>
          <br>
          <br>
          <br>
        <% end %>
      </div>
      <br>
      <nav class = "navbar fixed-bottom navbar-expand-lg navbar-light bg-light">
        <a class= "navbar-brand">Search for flights!</a>
        <%= form_tag "/flights/search/#{@vacation.id}", :method => "get", :class => "form-inline" do %>
          <label class = "my-1 mr-2">Origin:</label>
          <% if !@vacation.cur_city.nil? %>
            <strong><%= @vacation.cur_city.name %></strong>
            &ensp;
            &ensp;
            <%= hidden_field_tag "flight[origin_id]", @vacation.cur_city.id  %>
          <% else %>
            <%= collection_select :flight, :origin_id, @cities, :id, :name, {prompt: "Please select origin"}, {class: "form-control mr-sm-2"} %>
          <% end %>
          <label class = "my-1 mr-2"> Destination:</label>
          <%= collection_select :flight, :destination_id, @cities, :id, :name, {prompt: "Please select destination"}, {class: "form-control mr-sm-2"} %>
          <label class = "my-1 mr-2" >Departure Date:</label>
          <% if @vacation.hotels.empty? %>
            <% default = @vacation.start_date%>
          <% else %>
            <%default= @vacation.last_hotel_stay.check_out_time.to_date  %>
          <% end %>
          <%= date_field_tag("flight[start_time]", nil, {value: default, class: "form-control mr-sm-2 datetime-local"})%>
          <%= submit_tag 'Search', class: "btn btn-primary" %>
        <% end %>
      </nav>
    <% else %>
      <div class="col-sm button">
        <%= button_to "Delete the most recent flight", @most_recent_flight, {method: :delete, class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2", id: "delete-flight"} %>
        <br>
        <br>
        <br>
      </div>
      <div class="col-1 button">
      </div>
      <div class="col-sm button">
        <%= " "%>
      </div>
      <br>
    </div>
  </div>
  <nav class = "navbar fixed-bottom navbar-expand-lg navbar-light bg-light">
    <a class= "navbar-brand"> Add a hotel!</a>
    <%= form_for HotelStay.new, html: {class: "form-inline"}  do |f| %>
      <% hotel_list = Hotel.all.select do |hotel| %>
        <% hotel.city == @vacation.cur_city %>
      <% end%>
      <%= f.collection_select :hotel_id, hotel_list, :id, :name, {prompt: "Pick a hotel"}, {class: "form-control mr-sm-2"} %>
      <label class = "my-1 mr-2">Check in date (10:00 AM):</label>
      <%= f.date_field :check_in_time, :value => @vacation.last_flight.end_time.to_date, class: "form-control mr-sm-2 datetime-local" %>
      <label class = "my-1 mr-2">Check out date (06:00 PM):</label>
      <%= f.date_field :check_out_time, :value => @vacation.last_flight.end_time.to_date, class: "form-control mr-sm-2 datetime-local"%>
      <%= f.hidden_field :vacation_id, value: @vacation.id %>
      <%= f.submit "Book a hotel", class: "btn btn-primary"%>
    <% end %>
  </nav>
<% end %>

app/views/vacations/show_final.html.erb
<%= render "layouts/nav-bar" %>
<h1>FINALIZED</h1>
<h2 style='text-align:center'><%= "#{@vacation.name} starting on #{@vacation.start_date.strftime('%m/%d/%Y')} and ending on #{@vacation.end_date.strftime('%m/%d/%Y')}"%></h2>
<%= render "show-helper" %>